name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install Chrome
      run: ./.github/install-chrome.sh
    - name: Run tests
      run: sbt test
    - name: Archive test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: guidebook
        path: target/guidebook
